### ISSUE TITLE
No spaces between words at the end of long lines.

### ISSUE THREAD

**Issue by SoftwareApe** [janjoerke/vscode-align-by-regex#1]
When I have a text with long lines, e.g.

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea **commodo consequat**.
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id **est laborum**.

And I use align by regex, it aligns correctly but mashes together the words at the ends of long lines (I aligned by comma, but it doesn't render correctly on Github).

Lorem ipsum dolor sit amet                                                                                                                           , consectetur adipiscing elit                                  , sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea **commodoconsequat**.
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id **estlaborum**.

**Comment by SoftwareApe** [comment]
It's not necessarily only two words like in the example, sometimes it's three or four. And it also happens on multiple lines, not just on the first.

**Comment by janjoerke** [comment]
Hi, thank you for your feedback. I'll look into this, but it may take a while as i am currently very busy and don't know when i'll have the time.

**Comment by SoftwareApe** [comment]
I understand completely, I always write the same on my issues as well.
