### ISSUE TITLE
Unexpected Alignment 2

### ISSUE THREAD

**Issue by itaygr** [janjoerke/vscode-align-by-regex#10]
Here's an example:

Input:
```
a(123) // 123
bb(45)  // 45
ccc(6)   // 6
```

Align by Regex: \\(

Output:
```
a  (123) // 123
bb (45) // 45
ccc(6) // 6
```

Expected:
```
a  (123) // 123
bb (45)  // 45
ccc(6)   // 6
```

For some reason, the command changed the number of spaces *after* the match point.
The expectation is that everything after the match would remain unchanged, but only the match point will be aligned.

**Comment by janjoerke** [comment]
Thanks for your issue. This isse is fixed with 1.0.4.
