### ISSUE TITLE
Weird alignment on Markdown table

### ISSUE THREAD

**Issue by SoftwareApe** [janjoerke/vscode-align-by-regex#9]
I tried to align this table:

    I|have|a|table
    It|is|not|aligned

with Regex '\\|' and got the following:

    I |have|a|table
    It|is|not|aligned

**Comment by SoftwareApe** [comment]
Interestingly if the document is larger (some empty lines surrounding the table) it works:

    (empty)
    I|have|a|table
    It|is|not|aligned
    (empty)
    (empty)

turns into the expected

    (empty)
    I |have|a  |table
    It|is  |not|aligned
    (empty)
    (empty)

But only if I select all.

**Comment by SoftwareApe** [comment]
Found the mistake. I introduced it myself. I'm wondering how I didn't trigger it with any of the other testcases :/. Sorry mate.

**Comment by janjoerke** [comment]
I released your fix in 1.0.3.
